pragma Singleton
import QtQuick

QtObject {

    property color foreground: "#f1dedd"
    property color background: "#1a1111"
    property color cursor: "#f1dedd"
    property color primary: "#ffb3ae"
    property color onPrimary: "#571d1c"
    property color secondary: "#e7bdb9"
    property color onSecondary: "#442928"
    property color tertiary: "#e2c28c"
    property color onTertiary: "#402d04"
    property color surface: "#1a1111"
    property color surfaceBright: "#423736"
    property color error: "#ffb4ab"
    property color errorDim: "#ff8678"
    property color onError: "#690005"
    property color errorContainer: "#93000a"
    property color outline: "#a08c8b"
    property color shadow: "#000000"
    property color red: "#ffb4ab"
    property color redDim: "#ff8678"
    property color green: "#b7d085"
    property color greenDim: "#a1c260"
    property color yellow: "#dec56e"
    property color yellowDim: "#d5b444"
    property color blue: "#cebdfe"
    property color blueDim: "#a98bfd"
    property color magenta: "#fcb0d5"
    property color magentaDim: "#fa7fbb"
    property color cyan: "#84d5c4"
    property color cyanDim: "#5ec8b2"
    property color white: "#82d3e0"
}
