.pragma library

var data = {
    "position": "top",
    "launcherIcon": "",
    "launcherIconTint": true,
    "launcherIconFullTint": true,
    "launcherIconSize": 24,
    "pillStyle": "default",
    "screenList": [],
    "enableFirefoxPlayer": false,
    "barColor": [["surface", 0.0]],
    "frameEnabled": false,
    "frameThickness": 6,
    "pinnedOnStartup": true,
    "hoverToReveal": true,
    "hoverRegionHeight": 8,
    "showPinButton": true,
    "availableOnFullscreen": false,
    "use12hFormat": false,
    "containBar": false,
    "keepBarShadow": false,
    "keepBarBorder": false,
    "itemsLeft": ["launcher", "workspaces", "layout", "pin"],
    "itemsCenter": [],
    "centerItemsSplitByNotch": false,
    "itemsRight": ["presets", "tools", "systray", "controls", "battery", "clock", "power"],
    "itemsLeftVertical": ["launcher", "systray", "tools", "presets"],
    "itemsCenterVertical": ["layout", "workspaces", "pin"],
    "itemsRightVertical": ["controls", "battery", "clock", "power"]
}
